import { questions } from "@/data/questions";
import type { AssessmentResult, Faction, HollandKey, Scores, ValueKey } from "@/types";
const holland: HollandKey[] = ["R", "I", "A", "S", "E", "C"], values: ValueKey[] = ["stability", "achievement", "income", "freedom", "social"];
const copy: Record<Faction, string> = { "升学派": "你对成长与更高的平台有明确期待，适合把大学当作能力加速器。建议在大一就建立学习节奏和项目作品集，每学期留一项真实体验，去验证兴趣、认识行业。把好奇心变成研究能力，把目标拆成稳定行动，未来的选择权会越来越多。", "就业派": "你重视能力转化与真实世界的反馈，适合把大学当作职业试验场。建议在低年级尽早接触项目、比赛、实习和行业信息。收入目标没有问题，但真正决定上限的是可复用的专业能力、沟通能力和解决问题的能力。持续积累作品和人脉，让自己在变化里仍有选择。", "体制派": "你看重稳定、秩序与长期投入，这是一种成熟的风险意识。建议把基本功、证书和表达能力一起练起来，同时提前了解招录目录与地区差异。稳定并不等于被动等待：用实践验证真实场景，一步步打牢底盘。" };
function add(to: Record<string, number>, scores: Scores) { Object.entries(scores).forEach(([key, value]) => { to[key] = (to[key] || 0) + (typeof value === "number" ? value : 0); }); }
function normalized(raw: Record<string, number>, keys: readonly string[]) { return Object.fromEntries(keys.map((key) => { const possible = questions.reduce((sum, question) => sum + Math.max(...question.options.map((option) => option.scores[key as keyof Scores] || 0)), 0); return [key, possible ? Math.round(((raw[key] || 0) / possible) * 100) : 0]; })); }
export function computeResult(answers: number[][], duration: number): AssessmentResult { const raw: Record<string, number> = {}; answers.forEach((selected, index) => selected.forEach((option) => add(raw, questions[index]?.options[option]?.scores || {}))); const hollandScores = normalized(raw, holland) as Record<HollandKey, number>; const valueScores = normalized(raw, values) as Record<ValueKey, number>; const hollandCode = [...holland].sort((a, b) => hollandScores[b] - hollandScores[a]).slice(0, 3).join(""); const valuesRanking = [...values].sort((a, b) => valueScores[b] - valueScores[a]); const faction: Faction = valueScores.stability >= valueScores.achievement && valueScores.stability >= valueScores.income && valueScores.freedom <= valueScores.stability ? "体制派" : valueScores.income >= valueScores.achievement || (valueScores.income + valueScores.achievement >= 100 && valueScores.stability < valueScores.income) ? "就业派" : "升学派"; return { hollandCode, hollandScores, valueScores, valuesRanking, faction, factionDescription: copy[faction], duration }; }
export const valueLabels: Record<ValueKey, string> = { stability: "稳定感", achievement: "成长成就", income: "收入回报", freedom: "自主自由", social: "社会贡献" };
export const hollandLabels: Record<HollandKey, string> = { R: "实用型", I: "研究型", A: "艺术型", S: "社会型", E: "企业型", C: "常规型" };
